"""Localized UI strings for Telegram transport layer."""

from __future__ import annotations

from post_bot.shared.enums import InterfaceLanguage
from post_bot.shared.errors import InternalError, ValidationError


CATALOG: dict[InterfaceLanguage, dict[str, str]] = {
    InterfaceLanguage.EN: {
        "SYSTEM_READY": "System is ready.",
        "AVAILABLE_POSTS": "Available posts count: {available}.",
        "SELECT_INTERFACE_LANGUAGE": "👇Язык👇Language👇Idioma👇",
        "UPLOAD_PROMPT": "💬 Share bugs or ideas here — we reply quickly 🙌\nhttps://t.me/+exuWbQJ8pBFhMzEy\n\n📎Please upload your Excel file.",
        "THROTTLED_RETRY_SHORT": "Too many requests. Please try again in a few seconds.",
        "UPLOAD_TOO_FREQUENT": "You are uploading too often. Please wait a few seconds and try again.",
        "UPLOAD_FILE_TYPE_UNSUPPORTED": "Unsupported file type. Please upload an .xlsx Excel file.",
        "UPLOAD_FILE_TOO_LARGE": "File is too large. Maximum allowed size is {max_size_mb} MB.",
        "BUTTON_HOW_TO_USE": "How to use the bot",
        "BUTTON_UPLOAD_TASKS": "Upload tasks",
        "BUTTON_PUBLISH": "Publish",
        "BUTTON_DOWNLOAD_ARCHIVE": "Download archive",
        "APPROVAL_READY": "Materials are ready.",
        "APPROVAL_QUEUE_COUNT": "Tasks in queue: {count}",
        "APPROVAL_CHOOSE_ACTION": "Choose an action:",
        "APPROVAL_ALL_PROCESSED": "All materials are processed.",
        "APPROVAL_TIMEOUT_ARCHIVE_SENT": "Approval timed out. Sent one archive with {count} queued tasks.",
        "APPROVAL_PUBLISH_SUCCESS": "Publishing completed.",
        "APPROVAL_DOWNLOAD_SUCCESS": "Archive is ready for download.",
        "APPROVAL_DOWNLOAD_AFTER_PUBLISH_FORBIDDEN": "\u274c Cannot download archive after publication.",
        "APPROVAL_PUBLISH_AFTER_DOWNLOAD_FORBIDDEN": "\u274c Cannot publish archive after download.",
        "APPROVAL_ACTION_FAILED": "Action failed ({error_code}).",
        "PUBLISH_BOT_NOT_IN_CHANNEL": "Cannot send post because the bot is not added to the channel.",
        "VALIDATION_FAILED": "Validation failed.",
        "VALIDATION_ERRORS_TITLE": "File contains errors:",
        "VALIDATION_ERROR_ROW": "Row {excel_row}:",
        "VALIDATION_ERROR_ITEM": "- {column}: {message}",
        "VALIDATION_FIELD_TOO_LONG": "Field \"{field_name}\" exceeds {max_chars} characters (actual: {actual_length}). Fix the value and upload the file again.",
        "VALIDATION_REUPLOAD_HINT": "Fix the file and upload again.",
        "INSUFFICIENT_BALANCE": "Insufficient balance. Please purchase a package and upload again.",
        "INSUFFICIENT_BALANCE_WITH_COUNTS": "Insufficient balance. Required: {required}. Available: {available}.",
        "PROCESSING_STARTED": "Processing has started.",
    },
    InterfaceLanguage.RU: {
        "SYSTEM_READY": "Система готова.",
        "AVAILABLE_POSTS": "\u0414\u043e\u0441\u0442\u0443\u043f\u043d\u043e\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u043e\u0441\u0442\u043e\u0432: {available}.",
        "SELECT_INTERFACE_LANGUAGE": "Выберите язык интерфейса.",
        "UPLOAD_PROMPT": "💬 Пиши сюда любые баги или идеи — мы отвечаем быстро 🙌\nhttps://t.me/+exuWbQJ8pBFhMzEy\n\n📎Пожалуйста, загрузите Excel-файл.",
        "THROTTLED_RETRY_SHORT": "Слишком часто. Попробуйте снова через пару секунд.",
        "UPLOAD_TOO_FREQUENT": "Вы загружаете слишком часто. Подождите пару секунд и попробуйте снова.",
        "UPLOAD_FILE_TYPE_UNSUPPORTED": "Неподдерживаемый тип файла. Загрузите Excel-файл формата .xlsx.",
        "UPLOAD_FILE_TOO_LARGE": "Файл слишком большой. Максимальный размер: {max_size_mb} МБ.",
        "BUTTON_HOW_TO_USE": "Как пользоваться ботом",
        "BUTTON_UPLOAD_TASKS": "Загрузить задачи",
        "BUTTON_PUBLISH": "Опубликовать",
        "BUTTON_DOWNLOAD_ARCHIVE": "Скачать архив",
        "APPROVAL_READY": "Материалы готовы.",
        "APPROVAL_QUEUE_COUNT": "Задач в очереди: {count}",
        "APPROVAL_CHOOSE_ACTION": "Выберите действие:",
        "APPROVAL_ALL_PROCESSED": "Все материалы обработаны.",
        "APPROVAL_TIMEOUT_ARCHIVE_SENT": "Сессия подтверждения истекла. Отправлен один архив с задачами из очереди: {count}.",
        "APPROVAL_PUBLISH_SUCCESS": "Публикация завершена.",
        "APPROVAL_DOWNLOAD_SUCCESS": "Архив готов к скачиванию.",
        "APPROVAL_DOWNLOAD_AFTER_PUBLISH_FORBIDDEN": "\u274c \u041d\u0435\u043b\u044c\u0437\u044f \u0441\u043a\u0430\u0447\u0430\u0442\u044c \u0430\u0440\u0445\u0438\u0432 \u043f\u043e\u0441\u043b\u0435 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438.",
        "APPROVAL_PUBLISH_AFTER_DOWNLOAD_FORBIDDEN": "\u274c \u041d\u0435\u043b\u044c\u0437\u044f \u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u0442\u044c \u0430\u0440\u0445\u0438\u0432 \u043f\u043e\u0441\u043b\u0435 \u0441\u043a\u0430\u0447\u0438\u0432\u0430\u043d\u0438\u044f.",
        "APPROVAL_ACTION_FAILED": "Действие не выполнено ({error_code}).",
        "PUBLISH_BOT_NOT_IN_CHANNEL": "Невозможно отправить пост: бот не добавлен в канал.",
        "VALIDATION_FAILED": "Валидация не пройдена.",
        "VALIDATION_ERRORS_TITLE": "Файл содержит ошибки:",
        "VALIDATION_ERROR_ROW": "Строка {excel_row}:",
        "VALIDATION_ERROR_ITEM": "- {column}: {message}",
        "VALIDATION_FIELD_TOO_LONG": "Длина поля \"{field_name}\" превышает {max_chars} символов (фактически: {actual_length}). Исправьте значение и загрузите файл снова.",
        "VALIDATION_REUPLOAD_HINT": "Исправьте файл и загрузите снова.",
        "INSUFFICIENT_BALANCE": "Недостаточно баланса. Купите пакет и загрузите снова.",
        "INSUFFICIENT_BALANCE_WITH_COUNTS": "Недостаточно баланса. Нужно: {required}. Доступно: {available}.",
        "PROCESSING_STARTED": "Обработка запущена.",
    },
    InterfaceLanguage.UK: {
        "SYSTEM_READY": "Система готова.",
        "AVAILABLE_POSTS": "Available posts count: {available}.",
        "SELECT_INTERFACE_LANGUAGE": "Оберіть мову інтерфейсу.",
        "UPLOAD_PROMPT": "💬 Пиши сюди будь-які баги чи ідеї — ми відповідаємо швидко 🙌\nhttps://t.me/+exuWbQJ8pBFhMzEy\n\n📎Будь ласка, завантажте Excel-файл.",
        "THROTTLED_RETRY_SHORT": "Too many requests. Please try again in a few seconds.",
        "UPLOAD_TOO_FREQUENT": "You are uploading too often. Please wait a few seconds and try again.",
        "UPLOAD_FILE_TYPE_UNSUPPORTED": "Unsupported file type. Please upload an .xlsx Excel file.",
        "UPLOAD_FILE_TOO_LARGE": "File is too large. Maximum allowed size is {max_size_mb} MB.",
        "BUTTON_HOW_TO_USE": "Як користуватися ботом",
        "BUTTON_UPLOAD_TASKS": "Завантажити задачі",
        "BUTTON_PUBLISH": "Опублікувати",
        "BUTTON_DOWNLOAD_ARCHIVE": "Завантажити архів",
        "APPROVAL_READY": "Матеріали готові.",
        "APPROVAL_QUEUE_COUNT": "Задач у черзі: {count}",
        "APPROVAL_CHOOSE_ACTION": "Оберіть дію:",
        "APPROVAL_ALL_PROCESSED": "Усі матеріали оброблено.",
        "APPROVAL_TIMEOUT_ARCHIVE_SENT": "Сесію підтвердження завершено за таймаутом. Надіслано один архів із задачами черги: {count}.",
        "APPROVAL_PUBLISH_SUCCESS": "Публікацію завершено.",
        "APPROVAL_DOWNLOAD_SUCCESS": "Архів готовий до завантаження.",
        "APPROVAL_DOWNLOAD_AFTER_PUBLISH_FORBIDDEN": "\u274c Cannot download archive after publication.",
        "APPROVAL_PUBLISH_AFTER_DOWNLOAD_FORBIDDEN": "\u274c Cannot publish archive after download.",
        "APPROVAL_ACTION_FAILED": "Дію не виконано ({error_code}).",
        "PUBLISH_BOT_NOT_IN_CHANNEL": "Неможливо надіслати пост: бота не додано до каналу.",
        "VALIDATION_FAILED": "Валідацію не пройдено.",
        "VALIDATION_ERRORS_TITLE": "Файл містить помилки:",
        "VALIDATION_ERROR_ROW": "Рядок {excel_row}:",
        "VALIDATION_ERROR_ITEM": "- {column}: {message}",
        "VALIDATION_FIELD_TOO_LONG": "Довжина поля \"{field_name}\" перевищує {max_chars} символів (фактично: {actual_length}). Виправте значення і завантажте файл знову.",
        "VALIDATION_REUPLOAD_HINT": "Виправте файл і завантажте знову.",
        "INSUFFICIENT_BALANCE": "Недостатньо балансу. Купіть пакет і завантажте знову.",
        "INSUFFICIENT_BALANCE_WITH_COUNTS": "Недостатньо балансу. Потрібно: {required}. Доступно: {available}.",
        "PROCESSING_STARTED": "Обробку запущено.",
    },
    InterfaceLanguage.ES: {
        "SYSTEM_READY": "El sistema está listo.",
        "AVAILABLE_POSTS": "Available posts count: {available}.",
        "SELECT_INTERFACE_LANGUAGE": "Selecciona el idioma de la interfaz.",
        "UPLOAD_PROMPT": "💬 Escribe aquí cualquier bug o idea — respondemos rápido 🙌\nhttps://t.me/+exuWbQJ8pBFhMzEy\n\n📎Sube tu archivo Excel.",
        "THROTTLED_RETRY_SHORT": "Too many requests. Please try again in a few seconds.",
        "UPLOAD_TOO_FREQUENT": "You are uploading too often. Please wait a few seconds and try again.",
        "UPLOAD_FILE_TYPE_UNSUPPORTED": "Unsupported file type. Please upload an .xlsx Excel file.",
        "UPLOAD_FILE_TOO_LARGE": "File is too large. Maximum allowed size is {max_size_mb} MB.",
        "BUTTON_HOW_TO_USE": "Cómo usar el bot",
        "BUTTON_UPLOAD_TASKS": "Subir tareas",
        "BUTTON_PUBLISH": "Publicar",
        "BUTTON_DOWNLOAD_ARCHIVE": "Descargar archivo",
        "APPROVAL_READY": "Los materiales están listos.",
        "APPROVAL_QUEUE_COUNT": "Tareas en cola: {count}",
        "APPROVAL_CHOOSE_ACTION": "Elige una acción:",
        "APPROVAL_ALL_PROCESSED": "Todos los materiales están procesados.",
        "APPROVAL_TIMEOUT_ARCHIVE_SENT": "La sesión de aprobación expiró. Se envió un único archivo con tareas en cola: {count}.",
        "APPROVAL_PUBLISH_SUCCESS": "La publicación se completó.",
        "APPROVAL_DOWNLOAD_SUCCESS": "El archivo está listo para descargar.",
        "APPROVAL_DOWNLOAD_AFTER_PUBLISH_FORBIDDEN": "\u274c Cannot download archive after publication.",
        "APPROVAL_PUBLISH_AFTER_DOWNLOAD_FORBIDDEN": "\u274c Cannot publish archive after download.",
        "APPROVAL_ACTION_FAILED": "La acción falló ({error_code}).",
        "PUBLISH_BOT_NOT_IN_CHANNEL": "No se puede enviar la publicación porque el bot no está agregado al canal.",
        "VALIDATION_FAILED": "La validación falló.",
        "VALIDATION_ERRORS_TITLE": "El archivo contiene errores:",
        "VALIDATION_ERROR_ROW": "Fila {excel_row}:",
        "VALIDATION_ERROR_ITEM": "- {column}: {message}",
        "VALIDATION_FIELD_TOO_LONG": "La longitud del campo \"{field_name}\" supera {max_chars} caracteres (actual: {actual_length}). Corrige el valor y vuelve a subir el archivo.",
        "VALIDATION_REUPLOAD_HINT": "Corrige el archivo y vuelve a subirlo.",
        "INSUFFICIENT_BALANCE": "Saldo insuficiente. Compra un paquete y vuelve a subirlo.",
        "INSUFFICIENT_BALANCE_WITH_COUNTS": "Saldo insuficiente. Requerido: {required}. Disponible: {available}.",
        "PROCESSING_STARTED": "El procesamiento ha comenzado.",
    },
    InterfaceLanguage.ZH: {
        "SYSTEM_READY": "系统已就绪。",
        "AVAILABLE_POSTS": "Available posts count: {available}.",
        "SELECT_INTERFACE_LANGUAGE": "请选择界面语言。",
        "UPLOAD_PROMPT": "💬 任何 bug 或想法都可以发这里 — 我们回复很快 🙌\nhttps://t.me/+exuWbQJ8pBFhMzEy\n\n📎请上传您的 Excel 文件。",
        "THROTTLED_RETRY_SHORT": "Too many requests. Please try again in a few seconds.",
        "UPLOAD_TOO_FREQUENT": "You are uploading too often. Please wait a few seconds and try again.",
        "UPLOAD_FILE_TYPE_UNSUPPORTED": "Unsupported file type. Please upload an .xlsx Excel file.",
        "UPLOAD_FILE_TOO_LARGE": "File is too large. Maximum allowed size is {max_size_mb} MB.",
        "BUTTON_HOW_TO_USE": "如何使用机器人",
        "BUTTON_UPLOAD_TASKS": "上传任务",
        "BUTTON_PUBLISH": "发布",
        "BUTTON_DOWNLOAD_ARCHIVE": "下载归档",
        "APPROVAL_READY": "材料已准备好。",
        "APPROVAL_QUEUE_COUNT": "队列中的任务数：{count}",
        "APPROVAL_CHOOSE_ACTION": "请选择操作：",
        "APPROVAL_ALL_PROCESSED": "所有材料均已处理。",
        "APPROVAL_TIMEOUT_ARCHIVE_SENT": "审批会话已超时。已发送一个包含队列任务的归档：{count}。",
        "APPROVAL_PUBLISH_SUCCESS": "发布已完成。",
        "APPROVAL_DOWNLOAD_SUCCESS": "归档可供下载。",
        "APPROVAL_DOWNLOAD_AFTER_PUBLISH_FORBIDDEN": "\u274c Cannot download archive after publication.",
        "APPROVAL_PUBLISH_AFTER_DOWNLOAD_FORBIDDEN": "\u274c Cannot publish archive after download.",
        "APPROVAL_ACTION_FAILED": "操作失败（{error_code}）。",
        "PUBLISH_BOT_NOT_IN_CHANNEL": "无法发送帖子：机器人未添加到频道。",
        "VALIDATION_FAILED": "验证失败。",
        "VALIDATION_ERRORS_TITLE": "文件包含错误：",
        "VALIDATION_ERROR_ROW": "第 {excel_row} 行：",
        "VALIDATION_ERROR_ITEM": "- {column}: {message}",
        "VALIDATION_FIELD_TOO_LONG": "字段“{field_name}”长度超过 {max_chars} 个字符（实际：{actual_length}）。请修正后重新上传文件。",
        "VALIDATION_REUPLOAD_HINT": "请修复文件后重新上传。",
        "INSUFFICIENT_BALANCE": "余额不足。请购买套餐后重新上传。",
        "INSUFFICIENT_BALANCE_WITH_COUNTS": "余额不足。需要：{required}。可用：{available}。",
        "PROCESSING_STARTED": "处理已开始。",
    },
    InterfaceLanguage.HI: {
        "SYSTEM_READY": "सिस्टम तैयार है।",
        "AVAILABLE_POSTS": "Available posts count: {available}.",
        "SELECT_INTERFACE_LANGUAGE": "इंटरफ़ेस भाषा चुनें।",
        "UPLOAD_PROMPT": "💬 कोई भी बग या आइडिया यहाँ भेजें — हम जल्दी जवाब देते हैं 🙌\nhttps://t.me/+exuWbQJ8pBFhMzEy\n\n📎कृपया अपनी Excel फ़ाइल अपलोड करें।",
        "THROTTLED_RETRY_SHORT": "Too many requests. Please try again in a few seconds.",
        "UPLOAD_TOO_FREQUENT": "You are uploading too often. Please wait a few seconds and try again.",
        "UPLOAD_FILE_TYPE_UNSUPPORTED": "Unsupported file type. Please upload an .xlsx Excel file.",
        "UPLOAD_FILE_TOO_LARGE": "File is too large. Maximum allowed size is {max_size_mb} MB.",
        "BUTTON_HOW_TO_USE": "बॉट का उपयोग कैसे करें",
        "BUTTON_UPLOAD_TASKS": "टास्क अपलोड करें",
        "BUTTON_PUBLISH": "प्रकाशित करें",
        "BUTTON_DOWNLOAD_ARCHIVE": "आर्काइव डाउनलोड करें",
        "APPROVAL_READY": "सामग्री तैयार है।",
        "APPROVAL_QUEUE_COUNT": "क्यू में कार्य: {count}",
        "APPROVAL_CHOOSE_ACTION": "कार्रवाई चुनें:",
        "APPROVAL_ALL_PROCESSED": "सभी सामग्री प्रोसेस हो गई है।",
        "APPROVAL_TIMEOUT_ARCHIVE_SENT": "स्वीकृति सत्र टाइमआउट हो गया। कतार की {count} टास्क के साथ एक आर्काइव भेजा गया।",
        "APPROVAL_PUBLISH_SUCCESS": "प्रकाशन पूरा हुआ।",
        "APPROVAL_DOWNLOAD_SUCCESS": "आर्काइव डाउनलोड के लिए तैयार है।",
        "APPROVAL_DOWNLOAD_AFTER_PUBLISH_FORBIDDEN": "\u274c Cannot download archive after publication.",
        "APPROVAL_PUBLISH_AFTER_DOWNLOAD_FORBIDDEN": "\u274c Cannot publish archive after download.",
        "APPROVAL_ACTION_FAILED": "कार्रवाई विफल रही ({error_code}).",
        "PUBLISH_BOT_NOT_IN_CHANNEL": "पोस्ट भेजा नहीं जा सका: बॉट चैनल में नहीं जोड़ा गया है।",
        "VALIDATION_FAILED": "मान्यकरण विफल हुआ।",
        "VALIDATION_ERRORS_TITLE": "फ़ाइल में त्रुटियाँ हैं:",
        "VALIDATION_ERROR_ROW": "पंक्ति {excel_row}:",
        "VALIDATION_ERROR_ITEM": "- {column}: {message}",
        "VALIDATION_FIELD_TOO_LONG": "फ़ील्ड \"{field_name}\" की लंबाई {max_chars} अक्षरों से अधिक है (वास्तविक: {actual_length})। मान ठीक करके फ़ाइल दोबारा अपलोड करें।",
        "VALIDATION_REUPLOAD_HINT": "फ़ाइल ठीक करके फिर अपलोड करें।",
        "INSUFFICIENT_BALANCE": "बैलेंस पर्याप्त नहीं है। कृपया पैकेज खरीदें और फिर अपलोड करें।",
        "INSUFFICIENT_BALANCE_WITH_COUNTS": "बैलेंस पर्याप्त नहीं है। आवश्यक: {required}. उपलब्ध: {available}.",
        "PROCESSING_STARTED": "प्रोसेसिंग शुरू हो गई है।",
    },
    InterfaceLanguage.AR: {
        "SYSTEM_READY": "النظام جاهز.",
        "AVAILABLE_POSTS": "Available posts count: {available}.",
        "SELECT_INTERFACE_LANGUAGE": "اختر لغة الواجهة.",
        "UPLOAD_PROMPT": "💬 اكتب هنا أي أخطاء أو أفكار — نرد بسرعة 🙌\nhttps://t.me/+exuWbQJ8pBFhMzEy\n\n📎يرجى تحميل ملف Excel الخاص بك.",
        "THROTTLED_RETRY_SHORT": "Too many requests. Please try again in a few seconds.",
        "UPLOAD_TOO_FREQUENT": "You are uploading too often. Please wait a few seconds and try again.",
        "UPLOAD_FILE_TYPE_UNSUPPORTED": "Unsupported file type. Please upload an .xlsx Excel file.",
        "UPLOAD_FILE_TOO_LARGE": "File is too large. Maximum allowed size is {max_size_mb} MB.",
        "BUTTON_HOW_TO_USE": "كيفية استخدام البوت",
        "BUTTON_UPLOAD_TASKS": "تحميل المهام",
        "BUTTON_PUBLISH": "نشر",
        "BUTTON_DOWNLOAD_ARCHIVE": "تنزيل الأرشيف",
        "APPROVAL_READY": "المواد جاهزة.",
        "APPROVAL_QUEUE_COUNT": "المهام في الطابور: {count}",
        "APPROVAL_CHOOSE_ACTION": "اختر إجراءً:",
        "APPROVAL_ALL_PROCESSED": "تمت معالجة جميع المواد.",
        "APPROVAL_TIMEOUT_ARCHIVE_SENT": "انتهت جلسة الموافقة بالمهلة. تم إرسال أرشيف واحد يحتوي على مهام الطابور: {count}.",
        "APPROVAL_PUBLISH_SUCCESS": "اكتمل النشر.",
        "APPROVAL_DOWNLOAD_SUCCESS": "الأرشيف جاهز للتنزيل.",
        "APPROVAL_DOWNLOAD_AFTER_PUBLISH_FORBIDDEN": "\u274c Cannot download archive after publication.",
        "APPROVAL_PUBLISH_AFTER_DOWNLOAD_FORBIDDEN": "\u274c Cannot publish archive after download.",
        "APPROVAL_ACTION_FAILED": "فشل الإجراء ({error_code}).",
        "PUBLISH_BOT_NOT_IN_CHANNEL": "لا يمكن إرسال المنشور لأن البوت غير مضاف إلى القناة.",
        "VALIDATION_FAILED": "فشل التحقق.",
        "VALIDATION_ERRORS_TITLE": "الملف يحتوي على أخطاء:",
        "VALIDATION_ERROR_ROW": "الصف {excel_row}:",
        "VALIDATION_ERROR_ITEM": "- {column}: {message}",
        "VALIDATION_FIELD_TOO_LONG": "طول الحقل \"{field_name}\" يتجاوز {max_chars} حرفًا (فعليًا: {actual_length}). صحّح القيمة ثم أعد رفع الملف.",
        "VALIDATION_REUPLOAD_HINT": "يرجى إصلاح الملف ثم إعادة التحميل.",
        "INSUFFICIENT_BALANCE": "الرصيد غير كاف. يرجى شراء باقة ثم إعادة التحميل.",
        "INSUFFICIENT_BALANCE_WITH_COUNTS": "الرصيد غير كاف. المطلوب: {required}. المتاح: {available}.",
        "PROCESSING_STARTED": "بدأت المعالجة.",
    },
}


def parse_interface_language(raw: str) -> InterfaceLanguage:
    try:
        return InterfaceLanguage(raw)
    except ValueError as exc:
        raise ValidationError(
            code="INTERFACE_LANGUAGE_UNSUPPORTED",
            message="Unsupported interface language.",
            details={"value": raw},
        ) from exc


def get_message(language: InterfaceLanguage, key: str, **kwargs: object) -> str:
    lang_catalog = CATALOG.get(language)
    if lang_catalog is None:
        raise InternalError(
            code="I18N_LANGUAGE_CATALOG_MISSING",
            message="Language catalog is missing.",
            details={"language": language.value},
        )
    template = lang_catalog.get(key)
    if template is None:
        raise InternalError(
            code="I18N_KEY_MISSING",
            message="Localization key is missing.",
            details={"language": language.value, "key": key},
        )
    return template.format(**kwargs)




